dataset:
  repo_id: orange_apple_language # Repository ID
  root: ./demo_data_orange_apple # Your root for data file!
policy:
  type : smolvla
  chunk_size: 5
  n_action_steps: 5
  device: cuda
  
output_dir: ./ckpt/smolvla_omy # Save directory
batch_size: 16
job_name : smolvla_omy
resume: true
# config_path : ./ckpt/smolvla_omy/checkpoints/last/pretrained_model/train_config.json
seed : 42
num_workers: 8
steps: 20_000
eval_freq: -1 # No evaluation
log_freq: 50
save_checkpoint: true
save_freq: 10_000
use_policy_training_preset: true
  
wandb:
  enable: true
  project: smolvla_omy
  disable_artifact: true